NEW_BUTTON = 1 # "Új nyelv"
OPEN_BUTTON = 2 # "Nyit nyelv"
EXIT_BUTTON = 3 # "Ment"

FONT_DEFAULT = "Arial"
FONT_MONOSPACE = "Courier New"
FONT_ARIAL = "Arial"
FONT_COURIER_NEW = "Courier New"

FONT_SIZE_HEADING = 30
FONT_SIZE_SUBHEADING = 10
FONT_SIZE_DEFAULT = 10
FONT_SIZE_GUESS = 20
FONT_SIZE_LETTER_BUTTONS = 14

STANDARD_JUSTIFY = "center"

JUSTIFY = "center"

STICKY_WE = "we"
STICKY_NSEW = "nsew"
STICKY_N = "n"


COLOR_GREY = "grey"

WRAPLENGTH = "12cm"


TEXT_TOOL_TITLE = "Salsa"
TEXT_TOOL_DESCRIPTION = "Learn Spanish vocabulary the hard way."
TEXT_TOOL_VERSION = "v1.0.0"

CHAR_SPACE = " "

WRAPLENGTH = "12cm"